### PR TITLE
#1033 #1151 Lookup table fixes/improvements

### LINKED ISSUE #1033: Lookup tables problems
- [x] Should allow `_` characters in table name (or be more clear about how name is transformed)
- [x] Keep getting `Cannot read property 'value' of undefined` error (every 2nd time or so)
- [ ] Should interpret non-text fields as correct type (e.g. boolean or number)
- [x] Why is pluralising the table name entered -- this is inconsistent with other table naming, and confusing
- [x] Gets stuck importing large lists (> 2000, not sure exactly)
...

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #1033 (mostly)

Requires back-end branch from [PR #719](https://github.com/openmsupply/application-manager-server/pull/719)

Addresses all the items listed in #1033, except:
>  Should interpret non-text fields as correct type (e.g. boolean or number)

Need to be a bit careful with that. Even though I've already written a function to detect the Postgres type based on the content, I noticed some lookup tables had a mix of types (code for example is sometimes a number and sometimes text), so if we assumed that the first row was representative of the whole column, we'd cause problems. So will need to leave that for now until we can think it through a bit better, but it's not high priority for now.

The main importing error is fixed in the back-end.

I'll annotate my code with some comments to point out specific things.

Edit: Also chucked in a quick fix for #1151 cos it's so tiny 93343458

### CODE REVIEW

File: src/LookupTable/components/DownloadButton.tsx [hunk 1]
```diff
@@ -47,7 +49,7 @@ const DownloadButton = ({
         const url = window.URL.createObjectURL(new Blob([response.data]))
         const link = document.createElement('a')
         link.href = url
-        link.setAttribute('download', 'file.csv')
+        link.setAttribute('download', `${name}_${DateTime.now().toISODate()}.csv`)
```
Comment (CarlosNZ) [inline src/LookupTable/components/DownloadButton.tsx:52]: Downloaded file now has the table name and date in the name.

File: src/LookupTable/components/ImportCsvModal.tsx [hunk 2]
```diff
@@ -50,18 +49,16 @@ const ImportCsvModal: React.FC<any> = ({
     let formData: any = new FormData()
     formData.append('file', file)
 
-    const pluralTableName = pluralize.isPlural(tableName) ? tableName : pluralize.plural(tableName)
-
-    if (!tableStructureID) formData.append('tableName', pluralTableName)
+    if (!tableStructureID) formData.append('tableName', tableName)
```
Comment (CarlosNZ) [inline src/LookupTable/components/ImportCsvModal.tsx:52]: Got rid of all that plural nonsense -- tables are now saved as singular names, just like all the other tables in the database. However -- you *can* still name it a plural name if you want, just remember that Postgraphile expects singular named tables when generating the GraphQL schema.

File: src/LookupTable/components/ImportCsvModal.tsx [hunk 3]
```diff
@@ -50,18 +49,16 @@ const ImportCsvModal: React.FC<any> = ({
...
     const authHeader = JWT ? { Authorization: 'Bearer ' + JWT } : undefined
 
     await axios
       .post(
-        config.serverREST +
-          '/admin/lookup-table/import' +
-          (tableStructureID ? '/' + String(tableStructureID) : ''),
+        `${config.serverREST}/admin/lookup-table/import${
+          tableStructureID ? '/' + String(tableStructureID) : ''
+        }?tableName=${tableName}`,
```
Comment (CarlosNZ) [inline src/LookupTable/components/ImportCsvModal.tsx:61]: As mentioned in back-end PR, I'm passing the `tableName` as a query parameter since I couldn't extract it from `formData` with the changes to the file handling.

File: src/LookupTable/components/list/ListTable.tsx [hunk 4]
```diff
@@ -82,10 +82,11 @@ const ListTable: React.FC<any> = ({
                     <DownloadButton
                       popUpContent={strings.LOOKUP_TABLE_DOWNLOAD.replace('%1', lookupTable.label)}
                       id={lookupTable.id}
+                      name={lookupTable.label}
                     />
                   </Button.Group>
                 </Table.Cell>
-                <Table.Cell icon="chevron down" collapsing />
+                {/* <Table.Cell icon="chevron down" collapsing /> */}
```
Comment (CarlosNZ) [inline src/LookupTable/components/list/ListTable.tsx:89]: No idea what this was for. I'm assuming it was intended as a possible Accordion opener for some future implementation, so just hidden for now.

File: src/LookupTable/contexts/LookUpTableImportCsvContext.tsx [hunk 5]
```diff
@@ -49,8 +48,8 @@ const LookUpTableImportCsvReducer = (
     case LookUpTableImportCsvActions.ImportCSV:
       return { ...state, file: action.payload }
     case LookUpTableImportCsvActions.SetTableName: {
-      const removeNumbers = action.payload.replace(/([0-9])/gm, '')
-      return { ...state, tableName: camelCase(removeNumbers) }
+      const restrictCharacters = action.payload.replace(/[^A-z_]/gm, '')
```
Comment (CarlosNZ) [inline src/LookupTable/contexts/LookUpTableImportCsvContext.tsx:51]: Name can now be any alphabetical character or `_`. So you can write names in camelCase or snake_case as you see fit -- the database table name will always be converted to snake_case, but the "label" will be exactly what you enter.

File: src/LookupTable/hooks/useGetSingleTableStructure.hook.tsx [hunk 6]
```diff
@@ -28,7 +29,11 @@ const useGetTableStructure = (): LookupTableStructureType => {
 
   useEffect(() => {
     if (!loading && !error && data?.lookupTable) {
-      setStructure(data.lookupTable as any)
+      const lookupTable = data.lookupTable
+      const namePlural = pluralize.isPlural(lookupTable.name)
+        ? lookupTable.name
+        : pluralize.plural(lookupTable.name)
+      setStructure({ ...lookupTable, name: namePlural })
```
Comment (CarlosNZ) [inline src/LookupTable/hooks/useGetSingleTableStructure.hook.tsx:36]: I think the reason why table names were converted to plural is because the GraphQL schema has a pluralised node for returning multiple entities of a type (as in `application` for a single one and `applications`). However, forcing the table name to be plural actually *restricted* the GraphQL schema, cos you couldn't easily differentiate between a single item and a list of items, and being able to search by a single item is probably more likely within application forms.

So this addition here just converts the table name to plural form for querying the "multiple" node for that entity (e.g `products`)

File: package.json [hunk 7]
```diff
@@ -12,6 +12,7 @@
   },
   "scripts": {
     "dev": "webpack-dev-server --env.env=dev",
+    "start": "yarn dev",
```
Comment (CarlosNZ) [inline package.json:15]: Unrelated, but I keep getting mixed up between `yarn start` and `yarn dev` as different projects use different ones to start the dev app. So let's just allow both! 😄

File: src/containers/Outcomes/helpers.tsx [hunk 8]
```diff
@@ -87,7 +87,7 @@ export const getElementDetails = (value: any, displayDefinition: DisplayDefiniti
   const isAlreadyElement = !!formatting?.elementTypePluginCode
   const elementTypePluginCode = isAlreadyElement ? formatting?.elementTypePluginCode : 'shortText'
   const elementParameters = isAlreadyElement
-    ? formatting?.elementParameters
+    ? formatting?.elementParameters ?? {}
```
Comment (CarlosNZ) [inline src/containers/Outcomes/helpers.tsx:90]: Solves #1151
